/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      main: "#FEE5CA",
      primary: "#F9A28F",
      purple: "#51244B",
      shadow: "RGBA(40, 40, 40, 0.8)",
      dark: "#282828",
      bgDark: "#08040C",
      gray: "#838289",
      light: "#FFFFFF",
    },
    fontFamily: {
      fancy: ["Secular One", "sans-serif"],
      sans: ["Heebo", "sans-serif"],
      serif: ["Heebo", "sans-serif"],
      poppins: ["Heebo", "sans-serif"],
      display: ["Heebo", "sans-serif"],
      body: ["Heebo", "sans-serif"],
    },
    extend: {
      variants: {
        fill: ["hover", "focus"],
      },
      gridTemplateColumns: {
        "auto-1fr": "auto 1fr",
        "1fr-auto": "1fr auto",
        "auto-auto": "auto auto",
        "auto-auto-1fr": "auto auto 1fr",
        "auto-auto-auto-1fr": "auto auto auto 1fr",
        "auto-1fr-1fr": "auto 1fr 1fr",
        "1fr-2fr": "1fr 2fr;",
        "1fr-3fr": "1fr 3fr;",
        "2fr-1fr": "2fr 1fr;",
        "2fr-3fr": "2fr 3fr;",
        "auto-2fr-1fr": "auto 2fr 1fr",
        worlds: "1fr 1.4fr 1fr",
        "auto-1fr-auto": "auto 1fr auto",
        "8-auto": "auto auto auto auto auto auto auto 1fr",
        "7-auto": "auto auto auto auto auto auto 1fr",
        "6-auto": "auto auto auto auto auto 1fr",
        "5-auto": "auto auto auto auto 1fr",
        "4-auto": "auto auto auto 1fr",
      },
      gridTemplateRows: {
        "auto-1fr": "auto 1fr",
        "1fr-auto": "1fr auto",
        "1fr-9fr-1fr": "1fr 9fr 1fr",
        "1fr-1fr": "1fr 1fr",
        "1fr-2fr": "1fr 2fr",
        "2fr-1fr": "2fr 1fr",
        "1fr-8fr": "1fr 8fr",
        "auto-1fr-auto": "auto 1fr auto",
        "auto-auto-1fr": "auto auto 1fr",
        "1fr-1fr-auto": "1fr 1fr auto",
        "1fr-6fr-1fr": "1fr 6fr 1fr",
        "1fr-auto-auto": "1fr auto auto",
        "2-auto": "repeat(2, auto)",
        "3-auto": "repeat(3, auto)",
        "4-auto": "repeat(4, auto)",
      },
      gridAutoRows: {
        "1fr": "1fr",
      },
      borderRadius: {
        "homepage-bg": "40px 0px",
      },
      screens: {
        short: { raw: "(max-height: 920px)" },
        mdHeight: { raw: "(max-height: 1200px)" },
        lg: "1024px",
        xl: "1350px",
      },
    },
  },
  plugins: [],
};
